### PR TITLE
Support multiple arguments

### LINKED ISSUE #2: Support for multiple comma-separated arguments?
``` c++
dbg(42, "hello world");
```

### PR DESCRIPTION
**Pull request by ShikChen**
Fixes #2.

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution. This looks great!

I haven't reviewed it in detail, as there seem to be some issues:

* The tests on Windows currently fail with:
  ```
  [..macro\tests\demo.cpp:66 (main)] ====== multiple arguments
  [..macro\tests\demo.cpp:68 (main)] The number of arguments mismatch, please check unprotected comma
  [..macro\tests\demo.cpp:68 (main)] test_int, (std::vector<int>{2, 3, 4}), test_string = 42 (int&)
  [..macro\tests\demo.cpp:68 (main)] Y�����U��j�h�m� = {2, 3, 4} (std::vector<int>)
  ```
* The displayed types seem to have an additional reference attached as compared to before:
  before:
  ```
  [..macro/tests/demo.cpp:34 (main)] test_int = 42 (int)
  [..macro/tests/demo.cpp:35 (main)] test_float = 3.14 (const float)
  [..macro/tests/demo.cpp:36 (main)] test_bool = false (const bool)
  ```
  on this branch:
  ```
  [..macro/tests/demo.cpp:34 (main)] test_int = 42 (int&)
  [..macro/tests/demo.cpp:35 (main)] test_float = 3.14 (const float&)
  [..macro/tests/demo.cpp:36 (main)] test_bool = false (const bool&)
  ```

**Comment by ShikChen** [comment]
Thanks, I will try to fix those issues :)

**Comment by ShikChen** [comment]
Both issues should be fixed now. Please help review the PR, thanks :)

**Comment by sharkdp** [comment]
Thank you very much for the updates!

It might take some weeks until I find the time to properly review this.

**Comment by ShikChen** [comment]
Friendly ping :)

**Comment by ShikChen** [comment]
Thanks for the review!

**Pull request merged**
