### PR TITLE
Fix usage for compound types

### LINKED ISSUE #102: Broken output of containers
See example below.
https://godbolt.org/z/vnxaqq
```cpp
#include <dbg.h>

int main()
{
    std::vector<std::pair<std::string, int>> container = {
        {"30+2", 32}, {"30-2", 28}, {"30*2", 60}
    };
    dbg(container);
}
```
Here we have a vector of pairs of strings. Despite the library has pretty_print overloads for std::pair, std::string, and container they don't fully work with each other. It seems that the reason is the fact, that pretty_print overloads for std::pair and std::string are defined just after container overload and thus they aren't visible from pretty_print overload for containers.

A possible solution is adding declarations for all the pretty_print overloads before their definitions. For e.g. in my example, adding declarations for pair and string overloads before container overload fixes the problem.

```cpp
inline bool pretty_print(std::ostream& stream, const std::string& value);

template <typename T1, typename T2>
inline bool pretty_print(std::ostream& stream, const std::pair<T1, T2>& value);



template <typename Container>
inline typename std::enable_if<detail::is_container<const Container&>::value,
                               bool>::type
pretty_print(std::ostream& stream, const Container& value) {
```

### PR DESCRIPTION
**Pull request by YarikTH**
Fixes #102

TODO:
- [x] add missing tests
- [x] fix them using forward declaration of the functions

There are tons of pretty_print specializations and their combinations. I'm not sure it is worth testing all of them.

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution!

Concerning tests: I agree, we can not add tests for all possible combinations. But maybe it would be a good idea to add some tests that also check the output of pretty_print directly, instead of just calling dbg(..) without any check?

**Comment by YarikTH** [comment]
> Thank you very much for your contribution!
> 
> Concerning tests: I agree, we can not add tests for all possible combinations. But maybe it would be a good idea to add some tests that also check the output of pretty_print directly, instead of just calling dbg(..) without any check?
I think that testing the exact output of pretty print is a good idea, but I think it's a subject for a new PR and/or issue.
I don't understand half of the specializations of pretty_print, so it would be hard for me to write tests for them. And I have no idea which output of pretty_print is correct, I have almost zero experience in using the library.

**Comment by YarikTH** [comment]
I see.

**Comment by sharkdp** [comment]
I made the necessary changes. Hope that's fine for you.

**Pull request merged**
