### PR TITLE
Setting CMAKE_CXX_STANDARD to 11

### PR DESCRIPTION
**Pull request by amirmasoudabdol**
I had some difficulties compiling on macOS with AppleClang and realized that `CMAKE_CXX_STANDARD` is not set for the project. I think this should be set, and I believe if the project is embedded as a submodule, the standard will propagate to submodules from the root project, right? So, this should not cause any problem.

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for the feedback.

We are setting `CMAKE_CXX_STANDARD` here in `.travis.yml` to test against multiple C++ versions: https://github.com/sharkdp/dbg-macro/blob/c7424695eff81dd34c7a0614160492ce1b4f0c08/.travis.yml#L6-L40

Wouldn't this be affected (i.e. not work anymore)?

**Comment by amirmasoudabdol** [comment]
I don't think so, since you are manually overwriting it and CMake is going to replace the given value. 

That being said, I think there is room for improvement in the CMake. I couldn't compile your library with C98, and I see that you said it's C++11 compatible. Do you mean compatible or required? If it has to be compiled at least with C++11, then I think we can also set the [`CXX_STANDARD_REQUIRED`](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD_REQUIRED.html#prop_tgt:CXX_STANDARD_REQUIRED) after the [`CMAKE_CXX_STANDARD`](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html) to enforce that. This will stop the compilation if the user doesn't have a proper compiler. This also wouldn't affect your Travis config.

If you think this is a good idea, I can update the CMake and test it further.

**Comment by sharkdp** [comment]
By "C++11 compatible", I mean: `dbg(…)` can still be used with an 8-year-old version of C++ :smile:.
But you are right: C++11 is also required. I am not planning to support pre-C++11 versions.

**Comment by amirmasoudabdol** [comment]
I think the test would work fine as we are forcing the C++11. Let's see how the test works out then. I've adjusted the requirements, and I can see that I can compile with no problems.

**Comment by sharkdp** [comment]
I added the demo code. As you can see in Travis output,, my suspicion was correct and your change seems to force C++11.

**Comment by amirmasoudabdol** [comment]
I was wondering about that too. CMake documentation is very cryptic sometimes. I guess then we should just remove the `CMAKE_CXX_STANDARD_REQUIRED` and we should be good. CMake says if the standard doesn't exist, older standard will be selected.

**Comment by sharkdp** [comment]
I don't think that will work.

What we need is something like: *"if `CMAKE_CXX_STANDARD` is not set (via environment variable or by an enclosing `CMakeLists.txt`), set it to C++11"*.

**Comment by sharkdp** [comment]
I'm going to close this for the reasons given above. Also, there have been a few changes to the `CMakeLists` and the testing infrastructure.

**Pull request closed without merging**
