### PR TITLE
Add cmake package.

### PR DESCRIPTION
**Pull request by gwankyun**
```cmake
find_package(dbg_macro REQUIRED)

add_executable(${project})

target_sources(${project}
  PRIVATE
    src/main.cpp
)

target_link_libraries(${project} PRIVATE dbg_macro::dbg_macro)
```

### CODE REVIEW

**Comment by gwankyun** [comment]
@sharkdp Check it please.

**Comment by sharkdp** [comment]
How is this different from #108? See my comment there:

> Thank you for your contribution. Some description of what this provides would be nice.
This does multiple things at once and also modifies the source code. Can we make a separate PR for the code and the CMake changes?

**Comment by gwankyun** [comment]
> How is this different from #108? See my comment there:
> 
> > Thank you for your contribution. Some description of what this provides would be nice.
> > This does multiple things at once and also modifies the source code. Can we make a separate PR for the code and the CMake changes?

Close #108 please, this request only for CMake.

**Comment by sharkdp** [comment]
To be honest, I still don't understand what this gains us. Please add a proper description why we should merge this.

**Pull request closed without merging**
