### PR TITLE
perf test for dynamic disable vs compiled-out

### PR DESCRIPTION
**Pull request by asah**
tested with: `cmake -DCMAKE_CXX_STANDARD=11; make; ./dbg_macro-perf`

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for your contribution.

Quoting from HN:

> Would be nice to offer runtime enable/disable [...]. The key idea is that modern CPUs dynamically branch-predict-away if-statements that are rarely/never invoked, such as a dynamically disabled dbg() call.

What is the use case for this? `dbg(…)` calls were never really meant to be left inside the application. If you want to temporarily disable the `dbg(…)` output, you can redirect STDERR (`./programm 2> /dev/null`).

> With the performance difference magnified 10x by loop unrolling, this is what I'm seeing on my Mac laptop: 830000000 iterations in 3 secs = 2.76667e+08 iters/sec (compiled-out). 840000000 iterations in 3 secs = 2.8e+08 iters/sec (dynamically disabled).

I'm not sure if this benchmark is very representative for a typical `dbg(…)` usage. Also, I don't think that the call should be manually unrolled for benchmarking reasons. The optimization step in the compiler could revert all of this and turn it into a simple `if (…) { dbg(".."); dbg(".."); ...; dbg(".."); }`.

If I run your code in release mode, I get a negative output:
```
-1274967296 iterations in 3 secs = -4.24989e+08 iters/sec (compiled-out).
-1264967296 iterations in 3 secs = -4.21656e+08 iters/sec (dynamically disabled).
```
I guess the `int` is overflowing... 

PS: For micro benchmarks like this, I suggest to take a look at https://github.com/google/benchmark

**Comment by asah** [comment]
no worries - this initial PR was more to test your openness to dynamic dbg. As you can imagine, many apps use STERR for other things and wouldn't want to redirect it. Moreover, std I/O is very slow especially in large quantities.

If you're excited about dynamic dbg() then I'll work on the PR - if not, I'll delete it.

**Comment by sharkdp** [comment]
To be honest, I think I'd rather not include this in dbg-macro somehow. The API should essentially be just the macro invocation, nothing else. If there is something I'm not seeing here, let me know and I'm happy to discuss it.

Thank you!

**Comment by asah** [comment]
no worries at all - thanks for the quick look.

in terms of "just a macro" totally understand, and just to check - I assume
you know that it's possible to "have it both ways" where compile-out is
optional, i.e. only users who want dynamic get it, and everybody else has
compile-in or out...

best wishes - adam

**Pull request closed without merging**
